### ISSUE TITLE
Invite comrades to training

### ISSUE THREAD

**Issue by dantetemplar** [one-zero-eight/sport-bot#36] opened 2024-05-06 16:05 UTC
### Describe the feature

It would be nice to invite your friend to a workout via telegram. Perhaps this may be useful for trainers - they can forward the invitation to the local chat.

### Suggested solution

Button to generate invite with deep-linking to the training.

**Comment by evermake** [comment] 2024-05-06 18:52
Duplicate of #34.

**Closed by evermake** 2024-05-06 18:52 UTC
Labels: enhancement
